base_url = "https://pinchlime.com"
build_search_index = false
compile_sass = false
default_language = "zh-TW"
description = "介紹生產力工具，以及分享使用心得"
generate_feed = true
generate_rss = true
taxonomies = [
  {name = "tags"},
  {name = "categories"},
]
title = "Pin 起來！"

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
# highlight_theme = "Tomorrow"
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

smart_punctuation = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = false

[extra]
author = "P.J. Wu"
email = "mimir@hey.com"
theme_color = "#003c6d"

### THIRD PARTY
google_analytics = ""

### SOCIAL MEDIA
image = "https://pinchlime.com/logo.png"
twitter_user = "WuPingJu"

### I18N WORDS

[slugify]
paths = "on"
taxonomies = "on"

[translations]
keywords = "生產力工具, macOS, 專案管理, 任務管理, PM"
label_all_posts = "[看所有文章](/blog/)"
label_archive = "全部文章歸檔"
label_back_to_start = "本文開始"
label_book_author = "作者"
label_categories = "所有分類"
label_category = "分類"
label_created = "發布於"
label_home = "首頁"
label_links = "連結"
label_new_posts_list_title = "最新文章"
label_notes_title = "以下是我長期維護和更新的[筆記](/categories/notes/)："
label_published_on = "分類："
label_rating = "我的評分"
label_read_more = "繼續閱讀全文 ➞"
label_reading = "閱讀時間"
label_rss = "訂閱RSS"
label_table_contents = "目錄"
label_tag = "標籤"
label_tags = "標籤"
label_target_language = "English Blog"
label_taxonomy = "類別"
label_thoughts_title = "以下是我最近的幾則[短想法](/thoughts/)："
label_updated = "最後更新時間"
[languages.en]
description = "Introduce productivity tools"
generate_feed = true
generate_rss = true
highlight_code = true
smart_punctuation = true
taxonomies = [
  {name = "tags"},
  {name = "categories"},
]
title = "Pinchlime"
[languages.en.translations]
keywords = "Productivity Tools, Project Management, Product Management"
label_all_posts = "[View all posts](/en/blog/)"
label_archive = "Archive"
label_back_to_start = "Get Started"
label_book_author = "Book Author"
label_categories = "Categories"
label_category = "Category"
label_created = "Published"
label_home = "Home"
label_links = "Links"
label_new_posts_list_title = "Here are my [latest](/en/blog/) 10 articles:"
label_notes_title = "Here are the notes I have been [updating and maintaining for a long time](/en/categories/notes/):"
label_published_on = "on"
label_rating = "Rating"
label_read_more = "Continue to Read"
label_reading = "Reading Time"
label_rss = "Subscribe RSS"
label_table_contents = "On this page"
label_tag = "Tag"
label_tags = "Tags"
label_target_language = "中文網站"
label_taxonomy = "Taxonomy"
label_thoughts_title = "Here are a few of my latest [short thoughts](/en/thoughts/)："
label_updated = "Updated"
