base_url = "https://pinchlime.com"
build_search_index = false
compile_sass = false
default_language = "zh-TW"
description = "介紹生產力工具，以及分享使用心得"
generate_feeds = true
taxonomies = [
  {name = "categories", feed = true},
]
title = "Pin 起來！"
generate_sitemap = true
generate_robots_txt = true

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false

[extra]
author = "PJ Wu 吳秉儒"
email = "pj@pinchlime.com"
theme_color = "#003c6d"
image = "https://pinchlime.com/logo.png"
twitter_user = "@WuPingJu"

[slugify]
paths = "on"
taxonomies = "on"

[languages.zh-TW]
title = "Pin 起來！"
description = "介紹生產力工具，以及分享使用心得"

[languages.en]
title = "Pinchlime"
description = "Productivity tools and workflow articles"

