[[headers]]
    for = "/*"

    [headers.values]
    cache-control = '''
    public,
    max-age=0,
    must-revalidate'''

[build]
    publish = "public/"
    command = "zola build && npx pagefind@latest --source "public""
    

    [build.environment]
         ZOLA_VERSION = "0.16.0"