name: Zola Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: "0.19.2"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Zola
        run: |
          ZOLA_URL="https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "$ZOLA_URL" | tar -xz -C /tmp
          sudo mv /tmp/zola /usr/local/bin/zola
          zola --version
      - name: Build site
        run: zola build
